# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Alexis Soko
title: Software Engineer
email: alexissoko@gmail.com
website: www.github.com/alexissoko

# Social links
# twitter_username: facespics
github_username:  alexissoko
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: alexissoko
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Alexis and I'm a Software Engineer with a keen interest in automation and development with <mark>Python</mark>. I'm pragmatic. I have worked in  <mark>Agile</mark> environments. I have honed a deep analytical and coding skills on <mark>Data structures</mark> to efficiently implement solutions and find covert bugs.
  Statistical Learning newcomer to <mark>R</mark> and <mark>TensorFlow</mark>

  More skills: <mark>Django</mark>; <mark>PyTest</mark>; <mark>Linux</mark>; <mark>Java</mark>; <mark>Selenium</mark> and <mark>C#.Net</mark>
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Science History
   - Running
   - Futbol

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
